# Generated by Django 3.2.9 on 2021-11-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_company_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreationCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36)),
            ],
        ),
    ]
