# Generated by Django 3.2.9 on 2021-11-20 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_creationcodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Self',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='node.company')),
            ],
        ),
    ]
